// Next.js App Router doesn't have a literal <head> to patch — metadata is
// generated by the framework — so Harbor PWA hooks in through Next's own
// conventions instead of regex-editing JSX:
//  - app/icon.png + app/apple-icon.png — Next's file-convention icons,
//    auto-linked into every page's <head> at build time, no patch needed.
//  - app/manifest.ts — Next's file-convention manifest, auto-served at
//    /manifest.webmanifest and auto-linked, no patch needed.
//  - a small client component mounted in app/layout.tsx registers the
//    service worker — this is the one place layout.tsx is still touched,
//    and only ever to insert before the required literal </body> tag,
//    which every App Router root layout must render.

import type { PwaFormState } from "./types";

/** Directory portion of a layout path, e.g. "src/app/layout.tsx" -> "src/app/",
 * "app/layout.tsx" -> "app/". Root-relative (no leading slash), always ends
 * in "/" unless the path had no directory component. This is the single
 * source of truth for "what is this project's App Router root" — every
 * file-convention path (icon.png, apple-icon.png, manifest.ts) that must
 * live alongside layout.tsx is derived from it, so there is exactly one
 * place that can get "src/app" vs "app" wrong.
 */
export function appRouterDirOf(layoutPath: string): string {
  const idx = layoutPath.lastIndexOf("/");
  return idx === -1 ? "" : layoutPath.slice(0, idx + 1);
}

/** Where manifest.ts belongs for a given layout.tsx, per Next's file
 * convention: always the same App Router root as layout.tsx itself.
 * "app/layout.tsx" -> "app/manifest.ts"; "src/app/layout.tsx" ->
 * "src/app/manifest.ts". Never hardcode "app/manifest.ts" — that creates a
 * second, unserved "app/" root in any project using the src/app layout. */
export function nextManifestPathFor(layoutPath: string): string {
  return `${appRouterDirOf(layoutPath)}manifest.ts`;
}

export function generateNextManifestTs(form: PwaFormState, icon192Href: string, icon512Href: string): string {
  return `import type { MetadataRoute } from "next";

// Generated by Harbor PWA. Next.js serves this at /manifest.webmanifest
// and links it into every page automatically — no <head> edit needed.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: ${JSON.stringify(form.appName)},
    short_name: ${JSON.stringify(form.shortName || form.appName)},
    description: ${JSON.stringify(form.description || "")},
    start_url: ${JSON.stringify(form.startUrl || "/")},
    display: ${JSON.stringify(form.display)},
    background_color: ${JSON.stringify(form.backgroundColor)},
    theme_color: ${JSON.stringify(form.themeColor)},
    icons: [
      { src: ${JSON.stringify(icon192Href)}, sizes: "192x192", type: "image/png" },
      { src: ${JSON.stringify(icon512Href)}, sizes: "512x512", type: "image/png" },
    ],
  };
}
`;
}

export function generateRegisterSwComponent(swHref: string): string {
  const escaped = swHref.replace(/'/g, "\\'");
  return `"use client";

// Generated by Harbor PWA — registers the service worker on the client.
import { useEffect } from "react";

export default function HarborRegisterSW() {
  useEffect(() => {
    if ("serviceWorker" in navigator) {
      navigator.serviceWorker.register('${escaped}').catch(() => {});
    }
  }, []);
  return null;
}
`;
}

// Matches a single import statement, including multiline named imports
// ("import {\n  a,\n  b,\n} from '...'"), type-only imports, and both
// semicolon and no-semicolon styles. Deliberately non-greedy on the body so
// one bad match can't swallow the rest of the file.
const IMPORT_RE = /^import\s+(?:type\s+)?(?:[\s\S]*?)\bfrom\s+["'][^"']+["'];?/gm;
const BODY_CLOSE_RE = /<\/body>/i;
const REGISTER_TAG_RE = /<HarborRegisterSW\s*\/>/;
// A directive prologue entry: "use client" / 'use server' as its own
// statement, with or without a trailing semicolon, only valid at the very
// top of the file (only whitespace/comments may precede it).
const DIRECTIVE_RE = /^(\s*(?:\/\/[^\n]*\n|\/\*[\s\S]*?\*\/\s*)*)(["'])use (client|server)\2;?/;

export interface LayoutPatchResult {
  code: string;
  changed: boolean;
  notes: string[];
}

/** Inserts an import for the SW-registration component and mounts it right
 * before the layout's closing </body> — the one tag every App Router root
 * layout is required to render literally, unlike <head>. */
export function patchNextLayoutForServiceWorker(code: string, importPath: string): LayoutPatchResult {
  if (REGISTER_TAG_RE.test(code)) {
    return { code, changed: false, notes: ["sw_component_already_mounted"] };
  }
  if (!BODY_CLOSE_RE.test(code)) {
    return { code, changed: false, notes: ["layout_no_body_tag"] };
  }

  const importLine = `import HarborRegisterSW from "${importPath}";`;
  let next = code;

  // The directive prologue ("use client"/"use server") must stay the very
  // first statement in the file — inserting an import above it silently
  // changes the file's semantics (Next.js would stop treating it as a
  // client/server-directive-bearing module). Find the end of the prologue
  // first, and never insert an import before it.
  const directiveMatch = code.match(DIRECTIVE_RE);
  const prologueEnd = directiveMatch ? directiveMatch.index! + directiveMatch[0].length : 0;

  const matches = [...code.matchAll(IMPORT_RE)];
  const lastImportAfterPrologue = [...matches].reverse().find((m) => (m.index ?? 0) >= prologueEnd);

  if (lastImportAfterPrologue && lastImportAfterPrologue.index !== undefined) {
    const idx = lastImportAfterPrologue.index + lastImportAfterPrologue[0].length;
    next = next.slice(0, idx) + "\n" + importLine + next.slice(idx);
  } else {
    // No imports after the prologue (or no prologue at all) — insert right
    // after the directive, or at the very top if there isn't one.
    next = next.slice(0, prologueEnd) + (prologueEnd > 0 ? "\n" : "") + importLine + "\n" + next.slice(prologueEnd);
  }

  next = next.replace(BODY_CLOSE_RE, (m) => `<HarborRegisterSW />\n      ${m}`);
  return { code: next, changed: true, notes: [] };
}
