/**
 * A deliberately simple, safe service worker for static projects:
 * cache-first for same-origin GET requests, falling back to network, with
 * a versioned cache name so `activate` can clear out anything from a
 * previous Harbor PWA generation — this is the main defense against stale
 * cache getting stuck after the person redeploys.
 */
export function generateServiceWorkerSource(cacheVersion: string): string {
  return `// Generated by Harbor PWA — safe to regenerate any time.
const CACHE_NAME = "harbor-pwa-${cacheVersion}";

self.addEventListener("install", (event) => {
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key.startsWith("harbor-pwa-") && key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      )
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request)
        .then((response) => {
          if (response && response.status === 200) {
            const clone = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, clone));
          }
          return response;
        })
        .catch(() => cached);
    })
  );
});
`;
}

export function generateRegistrationSnippet(swPath: string): string {
  const escaped = swPath.replace(/</g, "\\u003C");
  return `<script>
    if ("serviceWorker" in navigator) {
      window.addEventListener("load", () => {
        navigator.serviceWorker.register("${escaped}").catch(() => {});
      });
    }
  </script>`;
}
