/**
 * Generated service worker. Cache policy is deliberately conservative:
 * generated SW code has no way to know which routes are user-specific, so
 * the default for anything that isn't a known-safe static asset is
 * "don't cache it" or "network-first" rather than "cache-first" —
 * see the classification helpers below (isApiRequest / isPrivateResponse /
 * isCacheableResponse) for the actual rules. The one thing that stays
 * cache-first is static assets (JS/CSS/fonts/images), which are safe by
 * construction: they're content-hashed or versioned by the framework's own
 * build, not user-specific, and caching them is what actually makes the
 * app usable offline.
 *
 * Principle (see Phase 3 spec §3.3): "not offline" is a better failure mode
 * than "shows stale or wrong data" — so anything ambiguous defaults to
 * network-first or network-only, never cache-first.
 */
export function generateServiceWorkerSource(cacheVersion: string): string {
  return `// Generated by Harbor PWA — safe to regenerate any time.
const CACHE_NAME = "harbor-pwa-${cacheVersion}";

self.addEventListener("install", (event) => {
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key.startsWith("harbor-pwa-") && key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      )
    )
  );
  self.clients.claim();
});

// --- Request/response classification -------------------------------------
// Kept as small, named predicates rather than one giant if-chain in the
// fetch handler, so each rule can be reasoned about (and tested) on its own.

// Same-origin API-shaped requests: never cache-worthy, may return
// user-specific or rapidly-changing data. "/api/" is the one convention we
// can safely assume across frameworks; this errs toward treating more
// requests as API-like rather than fewer.
function isApiRequest(url) {
  return /^\\/api(\\/|$)/.test(url.pathname);
}

// Explicit "do not cache me" signal from the server. Never assume GET means
// public — only cache when nothing tells us otherwise AND the response
// isn't marked private/no-store.
function isPrivateResponse(response) {
  const cacheControl = response.headers.get("cache-control") || "";
  return /(^|,)\\s*(private|no-store)\\s*(;|,|$)/i.test(cacheControl);
}

// Content-hashed/versioned static assets — safe to cache-first, but only
// when the request itself carries no credential signal (see
// isCredentialedRequest below). Extension alone is not enough: a request for
// "/image.png" sent with an Authorization header could still be returning a
// user-specific variant, so credentials always override the extension-based
// static-asset classification.
function isStaticAssetRequest(url) {
  return /\\.(?:js|mjs|css|woff2?|ttf|otf|eot|png|jpe?g|gif|webp|svg|ico|avif)$/i.test(url.pathname);
}

// Requests carrying an explicit credential signal we can actually see from
// a Service Worker. Cookies are deliberately not checked here: the Fetch
// spec forbids reading the Cookie header from JavaScript (including inside
// a Service Worker) precisely so scripts can't exfiltrate it, so an
// Authorization header and request.credentials are the only signals
// available. Treat either as "this request is not anonymous" and never
// cache-first it purely on extension.
function isCredentialedRequest(request) {
  if (request.headers && typeof request.headers.get === "function" && request.headers.get("Authorization")) return true;
  if (request.credentials === "include") return true;
  return false;
}

// Final gate before any cache.put(): every condition here must hold, or the
// response is never written to the cache.
function isCacheableResponse(response, apiRequest) {
  if (!response || !response.ok) return false;
  if (response.status !== 200) return false;
  if (apiRequest) return false;
  if (isPrivateResponse(response)) return false;
  return true;
}

function putInCache(request, response) {
  const clone = response.clone();
  caches.open(CACHE_NAME).then((cache) => cache.put(request, clone));
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  // Never cache non-GET (POST/PUT/PATCH/DELETE mutate state and are never
  // safe to serve from cache).
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  const apiRequest = isApiRequest(url);
  const credentialed = isCredentialedRequest(request);

  // API / private-data requests: network-only, bypass the cache entirely —
  // never read from it, never write to it.
  if (apiRequest) {
    event.respondWith(fetch(request));
    return;
  }

  // Any request carrying a credential signal (Authorization header, or
  // credentials: "include") is always network-only, no matter what it looks
  // like from the URL/extension alone — it may return a user-specific
  // response, and is never read from or written to the cache.
  if (credentialed) {
    event.respondWith(fetch(request));
    return;
  }

  // Static assets: cache-first — safe default, and what actually makes the
  // app usable offline.
  if (isStaticAssetRequest(url)) {
    event.respondWith(
      caches.match(request).then((cached) => {
        if (cached) return cached;
        return fetch(request).then((response) => {
          if (isCacheableResponse(response, apiRequest)) putInCache(request, response);
          return response;
        });
      })
    );
    return;
  }

  // Everything else (navigations, unknown same-origin GETs): network-first.
  // Only ever falls back to a previously-cached response if the network
  // fails outright, and only ever caches a fresh response that passed the
  // isCacheableResponse gate above — never blindly cache-first here.
  event.respondWith(
    fetch(request)
      .then((response) => {
        if (isCacheableResponse(response, apiRequest)) putInCache(request, response);
        return response;
      })
      .catch(() => caches.match(request).then((cached) => cached || Response.error()))
  );
});
`;
}

export function generateRegistrationSnippet(swPath: string): string {
  const escaped = swPath.replace(/</g, "\\u003C");
  return `<script>
    if ("serviceWorker" in navigator) {
      window.addEventListener("load", () => {
        navigator.serviceWorker.register("${escaped}").catch(() => {});
      });
    }
  </script>`;
}
