import type { ClientFile } from "@/lib/client-zip";
import type { ExistingServiceWorkerState } from "./detect/service-worker-detect";
import type { ExistingManifestState } from "./detect/manifest";

export type DisplayMode = "standalone" | "fullscreen" | "minimal-ui" | "browser";

/**
 * How Harbor PWA wires the manifest/icons/service-worker into the project.
 *
 * - "html-shell": there's a real file with a literal <head>...</head> (or JSX
 *   <Head>...</Head>) to inject tags into. Covers static HTML, Vite, CRA,
 *   Angular, SvelteKit, Astro, Gatsby (src/html.js), Remix (app/root), and
 *   Next.js Pages Router (pages/_document.tsx — created if it doesn't exist).
 * - "next-app-router": Next.js App Router has no literal <head> (metadata is
 *   generated by the framework), so Harbor PWA uses Next's own conventions
 *   instead: app/icon.png + app/apple-icon.png (auto-linked file convention)
 *   and a generated app/manifest.ts (auto-served + linked). app/layout.tsx is
 *   only ever touched to mount a small service-worker registration component
 *   right before the required literal </body> tag.
 * - "nuxt3": patches nuxt.config's `app.head` for the manifest/theme-color/
 *   icon tags, and adds a client plugin for service-worker registration.
 * - "unsupported": no reliable hook point was found. See `strategyNote`.
 */
export type PwaStrategy = "html-shell" | "next-app-router" | "nuxt3" | "unsupported";

export interface ProjectAnalysis {
  fileCount: number;
  totalBytes: number;
  framework: string | null;
  /** 0–1 confidence for `framework`, from evidence-based detection. 0 when
   * framework fell back to "Static HTML"/"Node.js"/null (no real evidence). */
  frameworkConfidence: number;
  /** Human-readable evidence strings backing `framework`, for diagnostics. */
  frameworkEvidence: string[];
  /** True if the project needs a build step (Next.js, Vite, CRA, ...) — Harbor PWA
   * still edits the source, but the person has to rebuild before deploying. */
  needsBuild: boolean;
  strategy: PwaStrategy;
  /** For "html-shell": the file Harbor PWA injects tags into. Null for the
   * other strategies — they don't do head injection at all. */
  entryHtmlPath: string | null;
  /** For "html-shell" only: true if entryHtmlPath doesn't exist yet in the
   * uploaded source and Harbor PWA needs to create it first (e.g. a Next.js
   * Pages Router project with no custom pages/_document.tsx). */
  entryHtmlNeedsCreate: boolean;
  /** For "next-app-router": app/layout.tsx (or .jsx/.js). For "nuxt3": nuxt.config.ts (or .js). Null otherwise. */
  configFilePath: string | null;
  /** Machine key explaining why strategy is "unsupported", for i18n lookup. Null otherwise. */
  strategyNote: string | null;
  hasPackageJson: boolean;
  /** Convenience path, derived from existingServiceWorker — null unless a
   * candidate was confidently detected (see existingServiceWorker for the
   * full semantic picture: confidence, registration, generator vs. real). */
  existingManifestPath: string | null;
  existingServiceWorkerPath: string | null;
  /** Full semantic detection result: path/confidence/sourceType/registered/registrationTarget. */
  existingServiceWorker: ExistingServiceWorkerState;
  existingManifest: ExistingManifestState;
  hasIcons: boolean;
  /** Folder to place generated icons/manifest into, e.g. "public" if one exists, else "". */
  assetRoot: string;
  suggestedStartUrl: string;
  suggestedAppName: string;
  suggestedDescription: string;
}

export type MutationAction = "CREATE" | "UPDATE" | "PRESERVE" | "SKIP" | "WARNING";

export interface MutationPlanEntry {
  path: string;
  action: MutationAction;
  reason: string;
}

export interface PwaFormState {
  appName: string;
  shortName: string;
  description: string;
  startUrl: string;
  themeColor: string;
  backgroundColor: string;
  display: DisplayMode;
  replaceManifest: boolean;
  replaceServiceWorker: boolean;
  /** Default false: preserve existing icons, only fill in missing ones. */
  replaceIcons: boolean;
}

export interface PwaIconSource {
  fileName: string;
  mimeType: string;
  /** Object URL for the live preview. */
  previewUrl: string;
  bytes: Uint8Array;
  isSquare: boolean;
  width: number;
  height: number;
}

export type GenerateStep =
  | "analyzing"
  | "icons"
  | "manifest"
  | "html"
  | "sw"
  | "packaging";

export interface GenerateResult {
  zipBlob: Blob;
  added: string[];
  updated: string[];
  unchanged: string[];
  /** Anything Harbor PWA couldn't wire up automatically — machine keys for i18n lookup. */
  manualSteps: string[];
  /** Explicit CREATE/UPDATE/PRESERVE/SKIP/WARNING decision per touched-or-considered path, computed before mutation. */
  mutationPlan: MutationPlanEntry[];
  /** Non-fatal OutputValidator findings (Phase 4 §2). Fatal findings never
   * reach this point — generatePwaPackage throws PwaValidationError instead
   * of returning a result, so a GenerateResult always represents a passed
   * validation. */
  validationWarnings: ValidationIssue[];
}

export interface ValidationIssue {
  severity: "error" | "warning";
  code: string;
  path?: string;
  detail: string;
}

export type { ClientFile };
