"use client";

// Generated by Harbor PWA — registers the service worker on the client.
import { useEffect } from "react";

export default function HarborRegisterSW() {
  useEffect(() => {
    if ("serviceWorker" in navigator) {
      navigator.serviceWorker.register('/service-worker.js').catch(() => {});
    }
  }, []);
  return null;
}
